/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * XDoclet definition:
 * @struts.form name="memberForm"
 */
public class MemberForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** phone property */
	private String phone;

	/** loginPwd property */
	private String loginPwd;

	/** loginName property */
	private String loginName;

	/** address property */
	private String address;

	/** memberlevel property */
	private Integer memberlevel;

	/** email property */
	private String email;

	/** zip property */
	private String zip;

	/** memberName property */
	private String memberName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the loginPwd.
	 * @return String
	 */
	public String getLoginPwd() {
		return loginPwd;
	}

	/** 
	 * Set the loginPwd.
	 * @param loginPwd The loginPwd to set
	 */
	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
	}

	/** 
	 * Returns the loginName.
	 * @return String
	 */
	public String getLoginName() {
		return loginName;
	}

	/** 
	 * Set the loginName.
	 * @param loginName The loginName to set
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/** 
	 * Returns the memberlevel.
	 * @return String
	 */
	public Integer getMemberlevel() {
		return memberlevel;
	}

	/** 
	 * Set the memberlevel.
	 * @param memberlevel The memberlevel to set
	 */
	public void setMemberlevel(Integer memberlevel) {
		this.memberlevel = memberlevel;
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the zip.
	 * @return String
	 */
	public String getZip() {
		return zip;
	}

	/** 
	 * Set the zip.
	 * @param zip The zip to set
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/** 
	 * Returns the memberName.
	 * @return String
	 */
	public String getMemberName() {
		return memberName;
	}

	/** 
	 * Set the memberName.
	 * @param memberName The memberName to set
	 */
	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}
}