/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * XDoclet definition:
 * @struts.form name="merForm"
 */
public class MerForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** manufacturer property */
	private String manufacturer;

	/** sprice property */
	private Double sprice;

	/** special property */
	private Integer special;

	/** leaveFactoryDate property */
	private String leaveFactoryDate;

	/** price property */
	private Double price;

	/** picture property */
	private FormFile picture;

	/** category property */
	private String category;

	/** merName property */
	private String merName;

	/** merModel property */
	private String merModel;

	/** merDesc property */
	private String merDesc;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the manufacturer.
	 * @return String
	 */
	public String getManufacturer() {
		return manufacturer;
	}

	/** 
	 * Set the manufacturer.
	 * @param manufacturer The manufacturer to set
	 */
	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	/** 
	 * Returns the sprice.
	 * @return double
	 */
	public Double getSprice() {
		return sprice;
	}

	/** 
	 * Set the sprice.
	 * @param sprice The sprice to set
	 */
	public void setSprice(Double sprice) {
		this.sprice = sprice;
	}

	/** 
	 * Returns the special.
	 * @return Integer
	 */
	public Integer getSpecial() {
		return special;
	}

	/** 
	 * Set the special.
	 * @param special The special to set
	 */
	public void setSpecial(Integer special) {
		this.special = special;
	}

	/** 
	 * Returns the leaveFactoryDate.
	 * @return String
	 */
	public String getLeaveFactoryDate() {
		return leaveFactoryDate;
	}

	/** 
	 * Set the leaveFactoryDate.
	 * @param leaveFactoryDate The leaveFactoryDate to set
	 */
	public void setLeaveFactoryDate(String leaveFactoryDate) {
		this.leaveFactoryDate = leaveFactoryDate;
	}

	/** 
	 * Returns the price.
	 * @return double
	 */
	public Double getPrice() {
		return price;
	}

	/** 
	 * Set the price.
	 * @param price The price to set
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/** 
	 * Returns the picture.
	 * @return FormFile
	 */
	public FormFile getPicture() {
		return picture;
	}

	/** 
	 * Set the picture.
	 * @param picture The picture to set
	 */
	public void setPicture(FormFile picture) {
		this.picture = picture;
	}

	/** 
	 * Returns the category.
	 * @return String
	 */
	public String getCategory() {
		return category;
	}

	/** 
	 * Set the category.
	 * @param category The category to set
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/** 
	 * Returns the merName.
	 * @return String
	 */
	public String getMerName() {
		return merName;
	}

	/** 
	 * Set the merName.
	 * @param merName The merName to set
	 */
	public void setMerName(String merName) {
		this.merName = merName;
	}

	/** 
	 * Returns the merModel.
	 * @return String
	 */
	public String getMerModel() {
		return merModel;
	}

	/** 
	 * Set the merModel.
	 * @param merModel The merModel to set
	 */
	public void setMerModel(String merModel) {
		this.merModel = merModel;
	}

	/** 
	 * Returns the merDesc.
	 * @return String
	 */
	public String getMerDesc() {
		return merDesc;
	}

	/** 
	 * Set the merDesc.
	 * @param merDesc The merDesc to set
	 */
	public void setMerDesc(String merDesc) {
		this.merDesc = merDesc;
	}
}